extends Node
class_name FeedbackConfig

# Master toggles (easy on/off for future config menus)
const ENABLE_DAMAGE_NUMBERS = true
const ENABLE_HIT_SPARKS = true
const ENABLE_CRIT_POP = true
const ENABLE_DEATH_FEEDBACK = true

# Damage numbers: pacing + readability
const DAMAGE_NUMBER_MIN = 1.0
const DAMAGE_NUMBER_COOLDOWN = 0.08 # seconds, per target
const DAMAGE_NUMBER_BUDGET_PER_SEC = 18
const DAMAGE_NUMBER_LIFETIME = 0.8
const DAMAGE_NUMBER_CRIT_LIFETIME = 1.1
const DAMAGE_NUMBER_DOT_LIFETIME = 0.45
const DAMAGE_NUMBER_RISE = 24.0
const DAMAGE_NUMBER_CRIT_RISE = 32.0
const DAMAGE_NUMBER_DOT_RISE = 12.0
const DAMAGE_NUMBER_JITTER_X = 10.0
const DAMAGE_NUMBER_JITTER_Y = 6.0
const DAMAGE_NUMBER_SCALE_MIN = 0.9
const DAMAGE_NUMBER_SCALE_MAX = 1.55
const DAMAGE_NUMBER_CRIT_SCALE_BONUS = 0.3
const DAMAGE_NUMBER_KILL_SCALE_BONUS = 0.2
const DAMAGE_NUMBER_ELITE_KILL_SCALE_BONUS = 0.5
const DAMAGE_NUMBER_SIZE_MULT = 1.5
const DAMAGE_NUMBER_POP_START = 0.6
const DAMAGE_NUMBER_POP_TIME = 0.1
const DAMAGE_NUMBER_POP_OVERSHOOT = 1.18
const DAMAGE_NUMBER_CRIT_POP_START = 0.52
const DAMAGE_NUMBER_CRIT_POP_TIME = 0.14
const DAMAGE_NUMBER_CRIT_POP_OVERSHOOT = 1.28
const DAMAGE_NUMBER_DOT_POP_START = 0.72
const DAMAGE_NUMBER_DOT_POP_TIME = 0.08
const DAMAGE_NUMBER_DOT_POP_OVERSHOOT = 1.1
const DAMAGE_NUMBER_FONT_SIZE = 16
const DAMAGE_NUMBER_CRIT_FONT_SIZE = 24
const DAMAGE_NUMBER_ROTATION_MAX = 0.06

const DAMAGE_NUMBER_FONT_PATH = "res://assets/ui/pixel_font.ttf"
const DAMAGE_NUMBER_OUTLINE_SIZE = 1
const DAMAGE_NUMBER_OUTLINE_COLOR = Color(0.043, 0.043, 0.043, 1.0)

const DAMAGE_COLOR_NORMAL = Color(1.0, 1.0, 1.0)
const DAMAGE_COLOR_CRIT = Color(1.0, 0.133, 0.533)
const DAMAGE_COLOR_DOT = Color(0.4, 1.0, 0.267)
const DAMAGE_COLOR_KILL = Color(1.0, 0.843, 0.0)
const DAMAGE_COLOR_ELITE_KILL = Color(0.8, 0.4, 1.0)
const DAMAGE_COLOR_FIRE = Color(1.0, 0.4, 0.133)
const DAMAGE_COLOR_ICE = Color(0.431, 0.922, 1.0)
const DAMAGE_COLOR_LIGHTNING = Color(0.267, 0.867, 1.0)
const DAMAGE_COLOR_BLEED = Color(0.769, 0.0, 0.169)
const DAMAGE_COLOR_HOLY = Color(1.0, 0.914, 0.651)
const DAMAGE_COLOR_SHADOW = Color(0.416, 0.173, 1.0)
const DAMAGE_COLOR_ARCANE = Color(0.271, 0.949, 1.0)

# Time scale accents
const KILL_SLOW_TIME_SCALE = 0.6
const KILL_SLOW_DURATION = 0.06
const TECH_SLOW_TIME_SCALE = 0.2

# Screen shake
const SCREEN_SHAKE_PLAYER_HIT = 6.0
const SCREEN_SHAKE_BUILDING_DESTROY = 10.0
const SCREEN_SHAKE_EXPLOSION = 8.0
const SCREEN_SHAKE_DURATION = 0.18

const DAMAGE_TYPE_COLORS = {
	"normal": DAMAGE_COLOR_NORMAL,
	"crit": DAMAGE_COLOR_CRIT,
	"dot": DAMAGE_COLOR_DOT,
	"poison": DAMAGE_COLOR_DOT,
	"acid": DAMAGE_COLOR_DOT,
	"fire": DAMAGE_COLOR_FIRE,
	"ice": DAMAGE_COLOR_ICE,
	"lightning": DAMAGE_COLOR_LIGHTNING,
	"bleed": DAMAGE_COLOR_BLEED,
	"holy": DAMAGE_COLOR_HOLY,
	"shadow": DAMAGE_COLOR_SHADOW,
	"arcane": DAMAGE_COLOR_ARCANE
}

# Crit rules (visual-only)
const CRIT_MIN_DAMAGE = 18.0
const CRIT_PCT_MAX_HEALTH = 0.35
const CRIT_PCT_ELITE = 0.25

# Hit sparks (visual-only)
const HIT_SPARK_MIN_DAMAGE = 1.0
const HIT_SPARK_COOLDOWN = 0.06
const PLAYER_HIT_SPARK_COOLDOWN = 0.12

# Hitstop (crit freeze frame)
const HITSTOP_TIME_SCALE = 0.05
const HITSTOP_DURATION = 0.1

# Death animation timings
const DEATH_FLASH_DURATION = 0.1
const DEATH_SCALE_DURATION = 0.3
const DEATH_FADE_DURATION = 0.2
const DEATH_CORPSE_FADE_DELAY = 3.0

# Screen effects
const SCREEN_SHAKE_BASE_INTENSITY = 1.0
const SCREEN_SHAKE_DAMAGE_MULTIPLIER = 0.15
const CHROMATIC_ABERRATION_DURATION = 0.25
const VIGNETTE_LOW_HP_THRESHOLD = 0.3

# Dynamic camera
const CAMERA_ENEMY_COUNT_THRESHOLD = 20
const CAMERA_ZOOM_OUT_AMOUNT = 0.9
const CAMERA_MOUSE_LEAN_AMOUNT = 30.0
const CAMERA_SMOOTH_SPEED = 4.0

# Projectile trails
const PROJECTILE_MOTION_BLUR_STRETCH = 1.5
const PROJECTILE_TRAIL_INTERVAL = 0.02

# Muzzle flash
const MUZZLE_FLASH_DURATION = 0.08
const SHELL_CASING_LIFETIME = 0.6
const IMPACT_SPARK_LIFETIME = 0.15

# Enhanced FX settings (new)
const PROJECTILE_TRAIL_FADE_TIME = 0.3
const PROJECTILE_TRAIL_WIDTH = 3.0
const PROJECTILE_TRAIL_MAX_POINTS = 12

const IMPACT_SPARK_COUNT_MIN = 4
const IMPACT_SPARK_COUNT_MAX = 8
const IMPACT_SPARK_COUNT_CRIT = 14
const GROUND_CRACK_FADE_TIME = 2.0

const DEATH_PARTICLE_COUNT = 12
const CORPSE_FADE_TIME = 1.0

const SHOCKWAVE_EXPAND_TIME = 0.4
const LIGHTNING_BEAM_LIFETIME = 0.15
const MULTISHOT_INDICATOR_LIFETIME = 0.25
