extends Node
class_name FeedbackConfig

# Master toggles (easy on/off for future config menus)
const ENABLE_DAMAGE_NUMBERS = true
const ENABLE_HIT_SPARKS = true
const ENABLE_CRIT_POP = true
const ENABLE_DEATH_FEEDBACK = true

# Damage numbers: pacing + readability
const DAMAGE_NUMBER_MIN = 1.0
const DAMAGE_NUMBER_COOLDOWN = 0.08 # seconds, per target
const DAMAGE_NUMBER_BUDGET_PER_SEC = 18
const DAMAGE_NUMBER_LIFETIME = 0.8
const DAMAGE_NUMBER_CRIT_LIFETIME = 1.1
const DAMAGE_NUMBER_DOT_LIFETIME = 0.45
const DAMAGE_NUMBER_RISE = 24.0
const DAMAGE_NUMBER_CRIT_RISE = 32.0
const DAMAGE_NUMBER_DOT_RISE = 12.0
const DAMAGE_NUMBER_JITTER_X = 10.0
const DAMAGE_NUMBER_JITTER_Y = 6.0
const DAMAGE_NUMBER_SCALE_MIN = 0.9
const DAMAGE_NUMBER_SCALE_MAX = 1.55
const DAMAGE_NUMBER_CRIT_SCALE_BONUS = 0.35
const DAMAGE_NUMBER_KILL_SCALE_BONUS = 0.2
const DAMAGE_NUMBER_ELITE_SCALE_BONUS = 0.08
const DAMAGE_NUMBER_POP_START = 0.85
const DAMAGE_NUMBER_POP_TIME = 0.08
const DAMAGE_NUMBER_CRIT_POP_START = 0.7
const DAMAGE_NUMBER_CRIT_POP_TIME = 0.12
const DAMAGE_NUMBER_DOT_POP_START = 0.9
const DAMAGE_NUMBER_DOT_POP_TIME = 0.06
const DAMAGE_NUMBER_FONT_SIZE = 12
const DAMAGE_NUMBER_CRIT_FONT_SIZE = 18
const DAMAGE_NUMBER_ROTATION_MAX = 0.06

const DAMAGE_NUMBER_FONT_PATH = "res://assets/ui/font_ui_gothic_ascii_12x16_v001.fnt"
const DAMAGE_NUMBER_OUTLINE_SIZE = 1
const DAMAGE_NUMBER_OUTLINE_COLOR = Color(0.043, 0.043, 0.043, 1.0)

const DAMAGE_COLOR_NORMAL = Color(0.969, 0.831, 0.29)
const DAMAGE_COLOR_CRIT = Color(1.0, 0.239, 0.604)
const DAMAGE_COLOR_DOT = Color(0.486, 1.0, 0.227)
const DAMAGE_COLOR_KILL = Color(1.0, 0.91, 0.39)
const DAMAGE_COLOR_FIRE = Color(1.0, 0.541, 0.165)
const DAMAGE_COLOR_ICE = Color(0.431, 0.922, 1.0)
const DAMAGE_COLOR_LIGHTNING = Color(1.0, 0.953, 0.416)
const DAMAGE_COLOR_BLEED = Color(0.769, 0.0, 0.169)
const DAMAGE_COLOR_HOLY = Color(1.0, 0.914, 0.651)
const DAMAGE_COLOR_SHADOW = Color(0.416, 0.173, 1.0)
const DAMAGE_COLOR_ARCANE = Color(0.271, 0.949, 1.0)

const DAMAGE_TYPE_COLORS = {
	"normal": DAMAGE_COLOR_NORMAL,
	"crit": DAMAGE_COLOR_CRIT,
	"dot": DAMAGE_COLOR_DOT,
	"poison": DAMAGE_COLOR_DOT,
	"acid": DAMAGE_COLOR_DOT,
	"fire": DAMAGE_COLOR_FIRE,
	"ice": DAMAGE_COLOR_ICE,
	"lightning": DAMAGE_COLOR_LIGHTNING,
	"bleed": DAMAGE_COLOR_BLEED,
	"holy": DAMAGE_COLOR_HOLY,
	"shadow": DAMAGE_COLOR_SHADOW,
	"arcane": DAMAGE_COLOR_ARCANE
}

# Crit rules (visual-only)
const CRIT_MIN_DAMAGE = 18.0
const CRIT_PCT_MAX_HEALTH = 0.35
const CRIT_PCT_ELITE = 0.25

# Hit sparks (visual-only)
const HIT_SPARK_MIN_DAMAGE = 1.0
const HIT_SPARK_COOLDOWN = 0.06
const PLAYER_HIT_SPARK_COOLDOWN = 0.12
