extends RefCounted
class_name RunManifest

# A run, as data.
#
# Before this, nothing in the project represented "a run". Everything was either
# fixed (the `characters` table in main.gd, the single level) or called global
# randi_range() at the point of use. The only seeded RNG in the codebase was
# descent.gd's starfield, hardcoded to 20260808.
#
# One integer decides the whole run: race, body, arrival, region, modifiers. Two
# runs with the same seed are the same run. NORTHSTAR.md calls that a design
# requirement rather than a nice-to-have, and the reason is testability: content
# rolled on global randi() cannot be given a negative control, so a procedural
# pivot on top of it would put the largest part of the game beyond the reach of
# the measure-don't-assume discipline the rest of this project runs on.
#
# TWO PROPERTIES ARE WORTH PROTECTING, because both are easy to lose by accident:
#
# 1. AXES ARE INDEPENDENT. Each axis draws from its own stream, derived from
#    (seed, axis-name) -- not from one sequential stream. If they shared a
#    stream, adding any new roll would silently re-deal every axis after it, so
#    every stored seed in every save file and bug report would decode to a
#    different run than the one it was recorded against. With named streams,
#    adding a modifier roll tomorrow leaves what seed 12345 gives you for race
#    and region untouched.
#
# 2. THE ARITHMETIC NEVER OVERFLOWS. All mixing happens on 31-bit operands, so
#    every product stays under 2^62 and inside int64 with room to spare. This is
#    not fussiness: a seed that wraps differently on two platforms is a seed that
#    does not mean the same thing on two machines, and the whole point of the
#    seed is that it does.
#
# roll() takes its tables as an argument rather than reaching for RiftDB. That is
# what lets tools/manifest_test.gd prove weighted selection against a synthetic
# table without inventing game content to test against.

# By path, not by the `RiftDB` global.
#
# A class_name is only resolvable once the project has been re-imported: the
# global class list lives in .godot/global_script_class_cache.cfg, which is
# gitignored and is not regenerated by --script. So on a fresh clone, or any time
# a script is added and a harness is run before the editor has opened, every
# class_name in the new file fails with "Identifier not found" -- including the
# file's own. That is what happened on this harness's first two runs, and it will
# happen to the next person who adds a script and runs a test before importing.
# Run `godot --headless --path . --import` once after adding a script.
#
# preload by path does not need the cache, so it works either way.
const Tables := preload("res://scripts/rift_db.gd")

const M31: int = 0x7FFFFFFF

# How many modifiers a region carries. Inclusive.
const MODIFIERS_MIN: int = 1
const MODIFIERS_MAX: int = 2

# The run in flight. A static var outlives a scene change, so intro.tscn and
# main.tscn read the same object without an autoload and without marshalling it
# through MetaProgression.
static var current: RunManifest = null

var seed: int = 0
var race_id: String = ""
var body_id: String = ""
var arrival_id: String = ""
var region_id: String = ""
var modifier_ids: Array[String] = []


# --- Seed derivation ----------------------------------------------------------

# djb2 over the axis name's UTF-8 bytes. h stays under 2^31 and the multiplier is
# 33, so the product cannot exceed 2^36.
static func _hash31(text: String) -> int:
	var h: int = 0x1505
	for b in text.to_utf8_buffer():
		h = ((h * 33) + int(b)) & M31
	return h


# 31-bit finalizer. Both operands of every multiply are masked to 31 bits, so the
# largest intermediate is under 2^62 -- no wrap, on any platform.
static func _mix31(v: int) -> int:
	var x: int = v & M31
	x = (x ^ (x >> 15)) & M31
	x = (x * 0x2FEB352D) & M31
	x = (x ^ (x >> 13)) & M31
	x = (x * 0x469CA68B) & M31
	x = (x ^ (x >> 16)) & M31
	return x


# The seed for one named axis. Two 31-bit halves composed into 62 bits, each
# mixed from a different part of the base seed, so seeds that differ only in
# their high bits still separate.
static func axis_seed(base: int, axis: String) -> int:
	var h: int = _hash31(axis)
	var lo: int = _mix31((base & M31) ^ h)
	var hi: int = _mix31(((base >> 31) & M31) ^ _mix31(h ^ 0x5A5A5A5))
	return (hi << 31) | lo


# A stream for one axis. Downstream systems that need many numbers -- region
# generation especially -- should take one of these rather than touch randi().
func rng_for(axis: String) -> RandomNumberGenerator:
	var rng := RandomNumberGenerator.new()
	rng.seed = axis_seed(seed, axis)
	return rng


# --- Selection ----------------------------------------------------------------

static func _weight_of(entry) -> float:
	if typeof(entry) != TYPE_DICTIONARY:
		return 0.0
	return maxf(0.0, float((entry as Dictionary).get("weight", 1)))


static func _pick(entries: Array, rng: RandomNumberGenerator) -> Dictionary:
	if entries.is_empty():
		return {}
	var total: float = 0.0
	for e in entries:
		total += _weight_of(e)
	if total <= 0.0:
		# Every weight is zero or absent-and-zero: fall back to uniform rather
		# than returning nothing, so a mis-authored table degrades instead of
		# producing an empty run.
		return entries[rng.randi_range(0, entries.size() - 1)]
	var target: float = rng.randf() * total
	var acc: float = 0.0
	for e in entries:
		acc += _weight_of(e)
		if target < acc:
			return e
	return entries[entries.size() - 1]


static func _pick_distinct(entries: Array, count: int, rng: RandomNumberGenerator) -> Array[String]:
	var out: Array[String] = []
	var pool: Array = entries.duplicate()
	var want: int = mini(count, pool.size())
	while out.size() < want:
		var chosen: Dictionary = _pick(pool, rng)
		var id: String = str(chosen.get("id", ""))
		if id == "":
			break
		out.append(id)
		pool.erase(chosen)
	return out


# --- Rolling ------------------------------------------------------------------

# Pure. Same (seed, tables) in, same manifest out, no globals touched.
static func roll(run_seed: int, tables: Dictionary) -> RunManifest:
	var m := RunManifest.new()
	m.seed = run_seed

	var races: Array = tables.get("races", [])
	var race: Dictionary = _pick(races, m.rng_for("race"))
	m.race_id = str(race.get("id", ""))

	# Body and arrival are rolled within the race, on their own streams. Arrivals
	# live under the race because "how they reached the Rift" is a property of
	# the culture (docs/RACE_BRIEF.md), not a free-floating axis.
	var bodies: Array = race.get("bodies", [])
	if not bodies.is_empty():
		var brng := m.rng_for("body")
		m.body_id = str(bodies[brng.randi_range(0, bodies.size() - 1)])

	var arrivals: Array = race.get("arrivals", [])
	m.arrival_id = str(_pick(arrivals, m.rng_for("arrival")).get("id", ""))

	m.region_id = str(_pick(tables.get("regions", []), m.rng_for("region")).get("id", ""))

	var mrng := m.rng_for("modifiers")
	var count: int = mrng.randi_range(MODIFIERS_MIN, MODIFIERS_MAX)
	m.modifier_ids = _pick_distinct(tables.get("modifiers", []), count, mrng)

	return m


static func roll_default(run_seed: int) -> RunManifest:
	return roll(run_seed, Tables.tables())


# Start a run and publish it. The only place `current` is assigned.
static func begin(run_seed: int) -> RunManifest:
	current = roll_default(run_seed)
	return current


# The PLAY press. Deals the whole hand for a new run -- lore, race, body,
# region, modifiers -- and forwards what the run scene consumes today through
# MetaProgression's pending fields, which main.gd and every harness already
# read. As more of the world becomes rolled (enemies, towers), this is the one
# place the forwarding grows.
#
# run_seed < 0 (the game's path) means deal at random; a harness passes a fixed
# seed and gets a provable hand.
static func deal(meta: Object, run_seed: int = -1) -> RunManifest:
	var m := begin(random_seed() if run_seed < 0 else run_seed)
	if meta != null:
		if "pending_hero" in meta:
			meta.pending_hero = m.body_id
		if "pending_level" in meta:
			meta.pending_level = str(m.region().get("terrain", "graveyard"))
	print("[RIFT] ", m.describe())
	return m


# The one deliberately non-deterministic call in this file. Everything else
# derives; this is where a fresh run gets its number, and it is isolated so it is
# obvious that nothing else rolls.
static func random_seed() -> int:
	return randi() & M31


# Accepts a player-typed seed. Digits are taken as the number so a shared seed
# round-trips exactly; anything else is hashed, so "brimstone" is a valid seed.
static func seed_from_text(text: String) -> int:
	var t := text.strip_edges()
	if t == "":
		return random_seed()
	if t.is_valid_int():
		return absi(t.to_int()) & M31
	return _mix31(_hash31(t))


# --- Access -------------------------------------------------------------------

func race() -> Dictionary:
	return Tables.get_race(race_id)


func region() -> Dictionary:
	return Tables.get_region(region_id)


func arrival() -> Dictionary:
	return Tables.get_arrival(race_id, arrival_id)


# The lines the intro types on arrival. Empty if the roll found no arrival, and
# the caller should treat that as "skip the beat", not as an error.
func arrival_lines() -> Array:
	return arrival().get("lines", [])


# The structures this run is allowed to build. A race is a tower vocabulary
# before it is anything else (NORTHSTAR.md, "Towers carry the world").
func available_towers() -> Array:
	return race().get("towers", [])


func to_dict() -> Dictionary:
	return {
		"seed": seed,
		"race": race_id,
		"body": body_id,
		"arrival": arrival_id,
		"region": region_id,
		"modifiers": modifier_ids.duplicate()
	}


func describe() -> String:
	return "seed=%d race=%s body=%s region=%s arrival=%s mods=[%s]" % [
		seed, race_id, body_id, region_id, arrival_id, ", ".join(modifier_ids)
	]
